"""Hand-maintained OpenAPI 3.0 spec for the API v1 layer.

Deliberately not generated by a schema-validation framework (no
apiflask/flask-smorest dependency added -- see
docs/superpowers/specs/2026-08-06-api-v1-foundation-design.md): each v1
endpoint contributes one entry to _PATHS as it's built, kept next to the
route it describes.
"""
from routes.v1 import api_v1_bp
from routes.v1.envelope import ok

def _get(summary: str, description: str) -> dict:
    return {"get": {"summary": summary,
                     "responses": {"200": {"description": description}}}}


_PATHS = {
    "/api/v1/": _get(
        "API root / liveness metadata",
        "Standard envelope with name/version/status",
    ),
    "/api/v1/status/jobs/running": _get(
        "Jobs currently executing",
        "Standard envelope wrapping {running: [...], count}",
    ),
    "/api/v1/status/jobs/latest": _get(
        "Most recent execution row per distinct job",
        "Standard envelope wrapping {jobs: [...]}",
    ),
    "/api/v1/status/jobs/failed": _get(
        "Failed job runs, newest first (optional ?since=)",
        "Standard envelope wrapping {failed: [...]}",
    ),
    "/api/v1/status/jobs/history": _get(
        "Recent execution history, newest first (optional ?limit=)",
        "Standard envelope wrapping {history: [...]}",
    ),
    "/api/v1/status/summary": _get(
        "Aggregate job counts by status",
        "Standard envelope wrapping {total, success, failed, skipped, running}",
    ),
    "/api/v1/scheduler": _get(
        "Live scheduler status",
        "Standard envelope wrapping {available, state, timezone, job_count}",
    ),
    "/api/v1/scheduler/jobs": _get(
        "All registered scheduler jobs, with next run + last run",
        "Standard envelope wrapping {jobs: [...], count}",
    ),
    "/api/v1/scheduler/jobs/{job_id}": _get(
        "A single scheduler job by id",
        "Standard envelope wrapping one job; 404 if job_id is unregistered",
    ),
    "/api/v1/metrics": _get(
        "Operational metrics rollup",
        "Standard envelope wrapping {jobs, engine, scheduler} -- same data as "
        "the three /metrics/* endpoints below, combined",
    ),
    "/api/v1/metrics/jobs": _get(
        "Job execution metrics",
        "Standard envelope wrapping {total, success, failed, skipped, running} "
        "-- identical data source to /api/v1/status/summary",
    ),
    "/api/v1/metrics/engine": _get(
        "Engine-level operational metrics",
        "Standard envelope wrapping {open_trades, signals_today_*, "
        "agent_decisions_today, ohlcv_tickers_today, market_risk_score, "
        "avg_vpin_today, last_scan_at}",
    ),
    "/api/v1/config": _get(
        "Build/release identity and static operational facts (read-only, "
        "allowlisted -- never secrets)",
        "Standard envelope wrapping {version, release_source, git_sha?, "
        "built_at?, database_backend, timezone, logging_level}",
    ),
    "/api/v1/config/runtime": _get(
        "Runtime mode / feature-flag surface (read-only, allowlisted -- "
        "never secrets)",
        "Standard envelope wrapping {auth_mode, edge_score_mode, "
        "sectors_app_mode, agent_firm_enabled, agent_firm_enforce, "
        "agent_firm_governor_enabled}",
    ),
}


def build_spec() -> dict:
    return {
        "openapi": "3.0.3",
        "info": {"title": "idx-walkforward-5001 API", "version": "v1"},
        "paths": dict(_PATHS),
    }


@api_v1_bp.route("/openapi.json", methods=["GET"])
def openapi_spec():
    return ok(build_spec())
