"""Hand-maintained OpenAPI 3.0 spec for the API v1 layer.

Deliberately not generated by a schema-validation framework (no
apiflask/flask-smorest dependency added -- see
docs/superpowers/specs/2026-08-06-api-v1-foundation-design.md): each v1
endpoint contributes one entry to _PATHS as it's built, kept next to the
route it describes.
"""
from routes.v1 import api_v1_bp
from routes.v1.envelope import ok

def _get(summary: str, description: str) -> dict:
    return {"get": {"summary": summary,
                     "responses": {"200": {"description": description}}}}


_PATHS = {
    "/api/v1/": _get(
        "API root / liveness metadata",
        "Standard envelope with name/version/status",
    ),
    "/api/v1/openapi.json": _get(
        "This OpenAPI spec itself",
        "Standard envelope wrapping {openapi, info, paths}",
    ),
    "/api/v1/status/jobs/running": _get(
        "Jobs currently executing",
        "Standard envelope wrapping {running: [...], count}",
    ),
    "/api/v1/status/jobs/latest": _get(
        "Most recent execution row per distinct job",
        "Standard envelope wrapping {jobs: [...]}",
    ),
    "/api/v1/status/jobs/failed": _get(
        "Failed job runs, newest first (optional ?since=)",
        "Standard envelope wrapping {failed: [...]}",
    ),
    "/api/v1/status/jobs/history": _get(
        "Recent execution history, newest first (optional ?limit=)",
        "Standard envelope wrapping {history: [...]}",
    ),
    "/api/v1/status/summary": _get(
        "Aggregate job counts by status",
        "Standard envelope wrapping {total, success, failed, skipped, running}",
    ),
    "/api/v1/scheduler": _get(
        "Live scheduler status",
        "Standard envelope wrapping {available, state, timezone, job_count}",
    ),
    "/api/v1/scheduler/jobs": _get(
        "All registered scheduler jobs, with next run + last run",
        "Standard envelope wrapping {jobs: [...], count}",
    ),
    "/api/v1/scheduler/jobs/{job_id}": _get(
        "A single scheduler job by id",
        "Standard envelope wrapping one job; 404 if job_id is unregistered",
    ),
    "/api/v1/metrics": _get(
        "Operational metrics rollup",
        "Standard envelope wrapping {jobs, engine, scheduler} -- same data as "
        "the three /metrics/* endpoints below, combined",
    ),
    "/api/v1/metrics/jobs": _get(
        "Job execution metrics",
        "Standard envelope wrapping {total, success, failed, skipped, running} "
        "-- identical data source to /api/v1/status/summary",
    ),
    "/api/v1/metrics/engine": _get(
        "Engine-level operational metrics",
        "Standard envelope wrapping {open_trades, signals_today_*, "
        "agent_decisions_today, ohlcv_tickers_today, market_risk_score, "
        "avg_vpin_today, last_scan_at}",
    ),
    "/api/v1/config": _get(
        "Build/release identity and static operational facts (read-only, "
        "allowlisted -- never secrets)",
        "Standard envelope wrapping {version, release_source, git_sha?, "
        "built_at?, database_backend, timezone, logging_level}",
    ),
    "/api/v1/config/runtime": _get(
        "Runtime mode / feature-flag surface (read-only, allowlisted -- "
        "never secrets)",
        "Standard envelope wrapping {auth_mode, edge_score_mode, "
        "sectors_app_mode, agent_firm_enabled, agent_firm_enforce, "
        "agent_firm_governor_enabled}",
    ),
    "/api/v1/health": _get(
        "Aggregated operational health -- deterministic, no new probes "
        "(reuses scheduler/metrics/configuration/release from "
        "2B-1/2B-2/2B-3 plus a minimal DB connectivity check)",
        "Standard envelope wrapping {overall: healthy|degraded|unavailable, "
        "components: {database, scheduler, metrics, configuration, release}}"
        " -- always HTTP 200, health state lives in the body, matching the "
        "existing /health route's convention",
    ),
    "/api/v1/watchlists/current": _get(
        "The latest firm-approved watchlist snapshot (optional ?strategy=, "
        "default 'eod'; also 'premarket')",
        "Standard envelope wrapping {strategy, date, watchlist: [...]}; "
        "404 NO_WATCHLIST_DATA if the strategy has no snapshot at all",
    ),
    "/api/v1/watchlists/history": _get(
        "Every date with a persisted watchlist snapshot for a strategy, "
        "newest first (optional ?strategy=)",
        "Standard envelope wrapping {strategy, dates: [...], count}",
    ),
    "/api/v1/watchlists/{date}": _get(
        "The watchlist snapshot for one exact date (optional ?strategy=)",
        "Standard envelope wrapping {strategy, date, watchlist: [...]}; "
        "404 NO_WATCHLIST_DATA if that date has no snapshot",
    ),
    "/api/v1/watchlists/diff": _get(
        "Diff for ?date= against its most recent prior snapshot (optional "
        "?strategy=) -- diff_watchlist()'s native semantics, not an "
        "arbitrary two-date comparison",
        "Standard envelope wrapping {strategy, date, diff}; diff is null "
        "(not an error) when date has no prior snapshot to compare against; "
        "400 MISSING_DATE if ?date= is absent; 404 NO_WATCHLIST_DATA if "
        "?date= itself has no snapshot",
    ),
    "/api/v1/watchlists/persistent": _get(
        "The multi-day accumulated approved-ticker watchlist (optional "
        "?status=active|removed|all, default active)",
        "Standard envelope wrapping {status, watchlist: [...], count}",
    ),
    "/api/v1/snapshots": _get(
        "Snapshot inventory/metadata across every snapshot-producing table "
        "(watchlist_snapshot + candidate_watchlist_snapshot) -- not "
        "content, see /api/v1/watchlists/* for that (optional "
        "?type=watchlist|candidate_universe, ?strategy=eod|premarket)",
        "Standard envelope wrapping {snapshots: [{type, strategy, date, "
        "ticker_count}], count}",
    ),
    "/api/v1/snapshots/{date}": _get(
        "Snapshot inventory/metadata for one exact date (optional ?type=, "
        "?strategy=)",
        "Standard envelope wrapping {date, snapshots: [...], count}; 404 "
        "NO_SNAPSHOT_DATA if that date has no snapshot of any type",
    ),
    "/api/v1/reports": _get(
        "The most recent Forward-Testing report (not necessarily today -- "
        "the latest date a report was actually generated)",
        "Standard envelope wrapping {date, new_positions, closed_trades, "
        "active_positions, active_candidates, win_loss, best_trades, "
        "worst_trades}; 404 NO_REPORT_DATA if no report has ever run",
    ),
    "/api/v1/reports/{date}": _get(
        "The Forward-Testing report for one exact date",
        "Same shape as GET /api/v1/reports; 404 NO_REPORT_DATA if the "
        "forward-test cycle never ran that date",
    ),
    "/api/v1/candidates": _get(
        "The latest pre-firm candidate universe snapshot",
        "Standard envelope wrapping {date, candidates: [...]}; 404 "
        "NO_CANDIDATE_DATA if nothing has ever been snapshotted",
    ),
    "/api/v1/candidates/{date}": _get(
        "The pre-firm candidate universe snapshot for one exact date",
        "Standard envelope wrapping {date, candidates: [...]}; 404 "
        "NO_CANDIDATE_DATA if that date has no snapshot",
    ),
    "/api/v1/candidates/screening": _get(
        "Daily technical/VPIN screening output (optional ?date=, default "
        "today) -- coexists with the still-consumed legacy "
        "GET /api/screener/results, same underlying data",
        "Standard envelope wrapping {date, results: [...], count}",
    ),
    "/api/v1/candidates/reversal-watchlist": _get(
        "Next-day delta-reversal day-trade candidates (optional ?date=, "
        "?direction=long|short) -- migrated from the removed legacy "
        "GET /api/screener/reversal",
        "Standard envelope wrapping {scan_date, count, long, short, "
        "results: [...]}",
    ),
    "/api/v1/candidates/premover-watchlist": _get(
        "Pre-mover breakout candidates (optional ?min_score=, ?days=, "
        "?pattern_type=) -- migrated from the removed legacy "
        "GET /api/premover/watchlist",
        "Standard envelope wrapping {count, watchlist: [...]}",
    ),
    "/api/v1/version": _get(
        "API/build/release version identity",
        "Standard envelope wrapping {api_version, release_version, "
        "release_source, git_sha?, built_at?, openapi_url}",
    ),
    "/api/v1/capabilities": _get(
        "Feature/capability flags -- what this server currently has "
        "enabled",
        "Standard envelope wrapping {auth_mode, edge_score_mode, "
        "sectors_app_mode, agent_firm_enabled, agent_firm_enforce, "
        "agent_firm_governor_enabled, resource_groups: [...]}",
    ),
    "/api/v1/resources": _get(
        "The full /api/v1 resource catalog, grouped by top-level "
        "resource -- read directly from this same _PATHS table, so it "
        "can never drift from the real route set",
        "Standard envelope wrapping {resources: [{name, endpoints: "
        "[{path, methods}]}]}",
    ),
    "/api/v1/registry/status": _get(
        "Edge Registry admission summary -- approved/shadow strategy "
        "counts and entries, read through the same engine.registry_loader "
        "cache every production admission check uses",
        "Standard envelope wrapping {hash, approved, shadow, entries: "
        "[{id, version, status, strategy_fn, regimes}], skipped_count, "
        "debt_count, violation_count}",
    ),
    "/api/v1/market/summary": _get(
        "Executive market summary -- composite risk score/tier plus the "
        "breadth, IHSG technicals, foreign flow, VPIN and accumulation/"
        "distribution sensors that feed it (optional ?date=, default "
        "today) -- same engine.dashboard.get_risk_dashboard() aggregator "
        "the legacy GET /api/dashboard/risk route already serves",
        "Standard envelope wrapping {date, risk_score, tier, components, "
        "ihsg, breadth, foreign_flow, vpin, accdist}; never 404s -- "
        "insufficient data degrades to a labelled empty sensor summary, "
        "not an error",
    ),
    "/api/v1/search/instruments": _get(
        "Instrument-code search over idx_tickers (required ?q=, optional "
        "?limit=, default 20) -- exact match ranked first, then prefix, "
        "then substring; no company-name search (idx_tickers has no name "
        "column)",
        "Standard envelope wrapping {query, results: [{ticker, in_idx30, "
        "in_lq45, in_idx80}], count}; 400 MISSING_QUERY if ?q= is absent "
        "or blank; zero matches is a valid 200 empty result, not an error",
    ),
}


def build_spec() -> dict:
    return {
        "openapi": "3.0.3",
        "info": {"title": "idx-walkforward-5001 API", "version": "v1"},
        "paths": dict(_PATHS),
    }


@api_v1_bp.route("/openapi.json", methods=["GET"])
def openapi_spec():
    return ok(build_spec())
